# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('isComplete', models.BooleanField(default=False, verbose_name='is completed')),
                ('priority', models.CharField(choices=[('HIG', 'high'), ('MED', 'medium'), ('LOW', 'low')], max_length=3)),
            ],
        ),
    ]
