# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_List', '0002_auto_20170423_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_item',
            name='priority',
            field=models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=3),
        ),
    ]
